trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 92a7f901-cc7b-48fb-a34f-d1929b8fef19
    scriptLocation: inlineScript
    scriptType: powershell
    inlineScript: 'az login'

- task: AzureCLI@2
  displayName: 'Get Resource List'
  inputs:
    azureSubscription: 92a7f901-cc7b-48fb-a34f-d1929b8fef19
    scriptLocation: inlineScript
    scriptType: powershell
    inlineScript: |
      # Get list of all resources
      $resources = az resource list --query "[?type!='Microsoft.Resources/deployments']" -o tsv
      
      # Exclude certain resource groups
      $excluded_groups = @("DefaultResourceGroup-EUS")
      foreach ($group in $excluded_groups) {
        $resources = $resources | Select-String -Pattern $group -NotMatch
      }
      
      $resources | Out-File -FilePath "$(Pipeline.Workspace)/resources.txt" -Encoding utf8

- task: PowerShell@7.2.0
  displayName: 'Send Email Notification'
  inputs:
    targetType: 'inline'
    script: |
      $emailTo = 'chandu.pavuluri@gmail.com'
      $emailFrom = 'support@cxpardise.com'
      $emailSubject = 'Azure Resource List'
      $smtpServer = 'smtp.office365.com'
      $smtpPort = 587
      
      $smtpUsername = '$(smtpUsername)'
      $smtpPassword = '$(smtpPassword)'
      $emailBody = @"
      The following resources have been found in your Azure subscription:

      $(Get-Content $(Pipeline.Workspace)/resources.txt)
      "@
      $emailParams = @{
          'To' = $emailTo
          'From' = $emailFrom
          'Subject' = $emailSubject
          'SmtpServer' = $smtpServer
          'SmtpPort' = $smtpPort
          'UseSSL' = $true
          'Credential' = New-Object System.Management.Automation.PSCredential ($smtpUsername, (ConvertTo-SecureString $smtpPassword -AsPlainText -Force))
          'Body' = $emailBody
      }
      Send-MailMessage @emailParams
